# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('svn_enname', models.CharField(max_length=10)),
                ('svn_company', models.CharField(max_length=20)),
                ('svn_zhname', models.CharField(max_length=200)),
                ('svn_url', models.CharField(max_length=100)),
            ],
        ),
    ]
