# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-17 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_name', models.CharField(max_length=10)),
                ('asset_number', models.CharField(max_length=20)),
                ('asset_source', models.CharField(max_length=10)),
                ('asset_people', models.CharField(max_length=100)),
                ('asset_application', models.CharField(max_length=100)),
            ],
        ),
    ]
