# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_application',
            new_name='asset_des_ip',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_number',
            new_name='asset_sou_ip',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_people',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_source',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_cron',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_des_dir',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_sou_dir',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
