# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-19 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_project', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=200, unique=True)),
                ('job_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Triggerbuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_build_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_status', models.CharField(max_length=200)),
                ('job_num', models.CharField(max_length=200)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Joblist')),
            ],
        ),
    ]
