# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerbuild',
            name='job_log',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
