# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0002_triggerbuild_job_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packageurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_url', models.CharField(max_length=500)),
                ('package_md5', models.CharField(max_length=100)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Triggerbuild')),
            ],
        ),
    ]
