# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0003_packageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageurl',
            name='package_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
