# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-25 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_name', models.CharField(max_length=10)),
                ('task_describe', models.CharField(max_length=20)),
                ('task_host', models.CharField(max_length=20)),
                ('task_command', models.CharField(max_length=200)),
            ],
        ),
    ]
